language: node_js   #设置语言
node_js: stable     #设置相应的版本

install:
  - npm install   #安装hexo及插件

script:
  - hexo cl   #清除
  - hexo g   #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "${GH_USERNAME}"   #修改成自己的github用户名
  - git config user.email "${GH_USEREMAIL}"   #修改成自己的GitHub邮箱
  - git add .
  - git commit -m "blog generate"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master #GH_token就是在travis中设置的token

branches:
  only:
  - source  #只监测这个分支，一有动静就开始构建
env:
  global:
    - GH_REF: ${GH_REF}